repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.265'
  hooks:
    - id: ruff
      args: ["--ignore=E501,F821"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: pretty-format-json
      args: ['--autofix', '--indent=2', '--no-sort-keys']
    - id: sort-simple-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
    - id: black
      args: ['--line-length=88']
